eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route 1: Content Service
        - id: content-service-routes
          uri: ${CONTENT_SERVICE_URL:lb://CONTENT-SERVICE}
          predicates:
            - Path=/api/v1/products,/api/v1/products/**,/api/v1/solutions,/api/v1/solutions/**,/api/v1/services,/api/v1/services/**,/api/v1/insights,/api/v1/insights/**,/api/v1/company,/api/v1/company/**,/api/v1/partners,/api/v1/partners/**,/api/v1/search,/api/v1/search/**,/api/v1/case-studies,/api/v1/case-studies/**,/api/v1/testimonials,/api/v1/testimonials/**,/api/v1/integrations,/api/v1/integrations/**,/api/v1/metrics,/api/v1/metrics/**

        # Route 2: Business Service
        - id: business-service-routes
          uri: ${BUSINESS_SERVICE_URL:lb://BUSINESS-SERVICE}
          predicates:
            - Path=/api/v1/industries,/api/v1/industries/**,/api/v1/careers,/api/v1/careers/**

        # Route 3: Contact Service
        - id: contact-service-routes
          uri: ${CONTACT_SERVICE_URL:lb://CONTACT-SERVICE}
          predicates:
            - Path=/api/v1/contact,/api/v1/contact/**
