server:
  port: ${PORT:8083}

spring:
  application:
    name: contact-service
  profiles:
    active: local
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_ENABLED:true}
    fetch-registry: ${EUREKA_CLIENT_ENABLED:true}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

resend:
  api:
    key: ${RESEND_API_KEY:}
  from: ${RESEND_FROM:onboarding@resend.dev}

contact:
  recipient: ${CONTACT_RECIPIENT:gorantlacjaran14@gmail.com}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
